expect_that(helper.function(), equals(NULL))
expect_that(calculateInstantaneousSlope(n.mom = NULL), equals(NULL))
expect_that(calculatePercentileRank(n.mom = NULL), equals(NULL))
expect_that(calculatePriceToSMADifferential(n.mom = NULL), equals(NULL))
expect_that(calculateSMADifferential(n.mom = NULL), equals(NULL))
expect_that(calculateTRMomentum(n.mom = NULL), equals(NULL))
expect_that(calculateTRx1Momentum(n.mom = NULL), equals(NULL))
expect_that(calculateZDistribution(n.mom = NULL), equals(NULL))
expect_that(calculateZScore(n.mom = NULL), equals(NULL))
expect_that(helper.function(), equals(NULL))
expect_that(runComboBacktest(), equals(NULL))
expect_that(runEqualWeightBacktest(momentum.matrix = NULL, n.positions = NULL, accumulate = NULL), equals(NULL))
expect_that(standardiseMomentumOverLookbacks(momentumfunc = NULL), equals(NULL))
